### ISSUE TITLE
Craft 4 version

### ISSUE THREAD

**Issue by bencroker** [guilty-as/craft-rss#4]
Hi there, do you plan on releasing a Craft 4 compatible version any time soon? Since I have a site using this plugin that I'd like to update to Craft 4, it would be much appreciated.

**Comment by bencroker** [comment]
Added a PR in https://github.com/guilty-as/craft-rss/pull/5.

**Comment by tomkiss** [comment]
@bencroker Hi Ben. This plugin uses the [Feeds API](https://docs.craftcms.com/api/v3/craft-feeds-feeds.html) which appears to be deprecated in Craft 4, so it won't work out-of-the-box.

As the craft-rss plugin appears to be abandoned, I've ported the Craft Feeds API code in to a [new plugin](https://github.com/dodecastudio/craft-feedreader), if you want to give it a go, let me know how you get on.

Incidentally, it's worth mentioning that for Craft 3, this plugin only appears to offer a shortcut to built-in functionality.

Rather than doing: `craft.rss.loadRss("https://helgesverre.com/blog/feed/")` you can just do:
`craft.app.feeds.getFeedItems("https://helgesverre.com/blog/feed/")` or:
`craft.app.feeds.getFeed("https://helgesverre.com/blog/feed/")` ...directly.

But those methods are not available in Craft 4 as they've been removed.

**Comment by bencroker** [comment]
Thanks @tomkiss, in the meantime I've found a workaround so won't be pursuing this further.

**Comment by hassanmah** [comment]
@bencroker can I ask what was the workaround? I'm having the same issue with upgrading to Craft 4

**Comment by bencroker** [comment]
@hassanmah I ended up just writing a Twig template with the RSS feed inside of it, named `feed.rss`.
